orbs:
  gradle: circleci/gradle@2.2.0
version: 2.1
workflows:
  build-test:
    jobs:
      - gradle/build
      - gradle/test
  check-linter:
    jobs:
      - gradle/ktlintCheck
  check-stage-task:
    jobs:
      - gradle/checkStage