orbs:
  gradle: circleci/gradle@2.2.0
version: 2.1

workflows:
  build-test:
    jobs:
      - gradle/test
      - gradle/run:
          command: ktlintCheck
      - gradle/run:
          command: checkStage
