version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: server/test-results/
  checkLinter:
    docker:
      - image: circleci/android:api-28
    steps:
      - run:
          name: Check KtLint
          command: ./gradlew ktlintCheck
  checkStageTask:
    docker:
      - image: circleci/android:api-28
    steps:
      - run:
          name: Check :stage Task
          command: ./gradlew checkStage