# Buy item in shop
# Request body: item id
POST {{host}}/shop/buyItem
Authorization: Bearer {{auth_token}}
Content-Type: application/json

1

###

# Get item data by id
GET {{host}}/shop/getItem?id=1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

# Get all items
GET {{host}}/shop/getAllItems
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

# Get all not owned items
GET {{host}}/shop/getNotOwnedItems
Authorization: Bearer {{auth_token}}
Content-Type: application/json
