GET {{host}}/me
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

POST {{host}}/changemyname
Authorization: Bearer {{auth_token}}
Content-Type: text/plain

new_name

###

POST {{host}}/changemyname
Authorization: Bearer {{auth_token}}
Content-Type: text/plain

name

###